title: Condent Public API
description: Öffentliche API-Dokumentation für die Integration von Dentist-Apps mit Condent.

remote_theme: just-the-docs/just-the-docs

color_scheme: dark
favicon_ico: /assets/images/favicon.ico

callouts:
  warning:
    title: Warnung
    color: yellow
  new:
    title: Neu
    color: green

# Exclude files not meant for the generated site
exclude:
  - README.md
